
server:
  port: 9001

#数据源配置
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch-cluster
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
logging:
  level:
    com.cxt.demo: debug

